// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const acquireIdempotency = `-- name: AcquireIdempotency :one
INSERT INTO idempotency_keys
    (user_id, idempotency_key, request_hash, lease_expires_at)
VALUES ($1, $2, $3, now() + interval '30 seconds')
ON CONFLICT (user_id, idempotency_key) DO UPDATE
SET request_hash     = EXCLUDED.request_hash,
    lease_expires_at = EXCLUDED.lease_expires_at,
    status_code      = 0,
    response_body    = NULL
WHERE (idempotency_keys.status_code = 0
       AND idempotency_keys.lease_expires_at < now())
   OR (idempotency_keys.status_code != 0
       AND idempotency_keys.created_at < now() - interval '24 hours')
RETURNING (xmax = 0) AS acquired,
          status_code, response_body, request_hash
`

type AcquireIdempotencyParams struct {
	UserID         uuid.UUID
	IdempotencyKey uuid.UUID
	RequestHash    string
}

type AcquireIdempotencyRow struct {
	Acquired     bool
	StatusCode   int32
	ResponseBody []byte
	RequestHash  string
}

// Atomically claim a fresh idempotency slot, or reclaim a stale (expired-lease)
// in-flight row, in a single round-trip.
//
//	acquired=true  → caller owns the lease, proceed to do the work
//	acquired=false + status_code != 0 → completed previously, replay it
//	no row returned → another caller holds an unexpired lease (409)
func (q *Queries) AcquireIdempotency(ctx context.Context, arg AcquireIdempotencyParams) (AcquireIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, acquireIdempotency, arg.UserID, arg.IdempotencyKey, arg.RequestHash)
	var i AcquireIdempotencyRow
	err := row.Scan(
		&i.Acquired,
		&i.StatusCode,
		&i.ResponseBody,
		&i.RequestHash,
	)
	return i, err
}

const completeIdempotency = `-- name: CompleteIdempotency :exec
UPDATE idempotency_keys
SET status_code = $3, response_body = $4
WHERE user_id = $1 AND idempotency_key = $2
`

type CompleteIdempotencyParams struct {
	UserID         uuid.UUID
	IdempotencyKey uuid.UUID
	StatusCode     int32
	ResponseBody   []byte
}

func (q *Queries) CompleteIdempotency(ctx context.Context, arg CompleteIdempotencyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotency,
		arg.UserID,
		arg.IdempotencyKey,
		arg.StatusCode,
		arg.ResponseBody,
	)
	return err
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT status_code, response_body, request_hash, lease_expires_at
FROM idempotency_keys
WHERE user_id = $1 AND idempotency_key = $2
`

type GetIdempotencyParams struct {
	UserID         uuid.UUID
	IdempotencyKey uuid.UUID
}

type GetIdempotencyRow struct {
	StatusCode     int32
	ResponseBody   []byte
	RequestHash    string
	LeaseExpiresAt pgtype.Timestamptz
}

// Used after an Acquire returns no row, to fetch the completed/in-flight record.
func (q *Queries) GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (GetIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotency, arg.UserID, arg.IdempotencyKey)
	var i GetIdempotencyRow
	err := row.Scan(
		&i.StatusCode,
		&i.ResponseBody,
		&i.RequestHash,
		&i.LeaseExpiresAt,
	)
	return i, err
}
