// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_logs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertTaskLog = `-- name: InsertTaskLog :exec
INSERT INTO task_logs (task_id, actor_id, action, payload)
VALUES ($1, $2, $3, $4)
`

type InsertTaskLogParams struct {
	TaskID  uuid.UUID
	ActorID uuid.UUID
	Action  string
	Payload []byte
}

func (q *Queries) InsertTaskLog(ctx context.Context, arg InsertTaskLogParams) error {
	_, err := q.db.Exec(ctx, insertTaskLog,
		arg.TaskID,
		arg.ActorID,
		arg.Action,
		arg.Payload,
	)
	return err
}

const listTaskLogs = `-- name: ListTaskLogs :many
SELECT id, task_id, actor_id, action, payload, created_at FROM task_logs
WHERE task_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTaskLogs(ctx context.Context, taskID uuid.UUID) ([]TaskLog, error) {
	rows, err := q.db.Query(ctx, listTaskLogs, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskLog{}
	for rows.Next() {
		var i TaskLog
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ActorID,
			&i.Action,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
