// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (team_id, created_by, assignee_id, title, description, status, priority, due_date)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, team_id, created_by, assignee_id, title, description, status, priority, due_date, created_at, updated_at
`

type CreateTaskParams struct {
	TeamID      uuid.UUID
	CreatedBy   uuid.UUID
	AssigneeID  *uuid.UUID
	Title       string
	Description string
	Status      TaskStatus
	Priority    TaskPriority
	DueDate     pgtype.Timestamptz
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.TeamID,
		arg.CreatedBy,
		arg.AssigneeID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.CreatedBy,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, team_id, created_by, assignee_id, title, description, status, priority, due_date, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.CreatedBy,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskForUpdate = `-- name: GetTaskForUpdate :one
SELECT id, team_id, created_by, assignee_id, title, description, status, priority, due_date, created_at, updated_at FROM tasks WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetTaskForUpdate(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskForUpdate, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.CreatedBy,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, team_id, created_by, assignee_id, title, description, status, priority, due_date, created_at, updated_at, count(*) OVER () AS total
FROM tasks
WHERE team_id = $1
  AND ($2::task_status IS NULL OR status = $2::task_status)
  AND ($3::text = '' OR title ILIKE '%' || $3 || '%')
ORDER BY created_at DESC
LIMIT $5
OFFSET $4
`

type ListTasksParams struct {
	TeamID       uuid.UUID
	StatusFilter *TaskStatus
	Q            string
	Off          int32
	Lim          int32
}

type ListTasksRow struct {
	ID          uuid.UUID
	TeamID      uuid.UUID
	CreatedBy   uuid.UUID
	AssigneeID  *uuid.UUID
	Title       string
	Description string
	Status      TaskStatus
	Priority    TaskPriority
	DueDate     pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	Total       int64
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]ListTasksRow, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.TeamID,
		arg.StatusFilter,
		arg.Q,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksRow{}
	for rows.Next() {
		var i ListTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.CreatedBy,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET title       = $2,
    description = $3,
    status      = $4,
    priority    = $5,
    due_date    = $6,
    updated_at  = now()
WHERE id = $1
RETURNING id, team_id, created_by, assignee_id, title, description, status, priority, due_date, created_at, updated_at
`

type UpdateTaskParams struct {
	ID          uuid.UUID
	Title       string
	Description string
	Status      TaskStatus
	Priority    TaskPriority
	DueDate     pgtype.Timestamptz
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.CreatedBy,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskAssignee = `-- name: UpdateTaskAssignee :one
UPDATE tasks
SET assignee_id = $2, updated_at = now()
WHERE id = $1
RETURNING id, team_id, created_by, assignee_id, title, description, status, priority, due_date, created_at, updated_at
`

type UpdateTaskAssigneeParams struct {
	ID         uuid.UUID
	AssigneeID *uuid.UUID
}

func (q *Queries) UpdateTaskAssignee(ctx context.Context, arg UpdateTaskAssigneeParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskAssignee, arg.ID, arg.AssigneeID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.CreatedBy,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
